### ISSUE TITLE
Running the code without Docker

### ISSUE THREAD

**Issue by LucasNLiborio** [faisalthaheem/machine-learnt-air-conditioning#2]
Hello, I've been trying to run the learning process without using the actual Docker containers, by now I was able to build the image and run node-red, the problem that I am facing is with the following piece of command:
```
docker run -d -p 5000:5000 --name ltrest \
-e mongodbhost=192.168.100.100 \
--restart unless-stopped \
faisalthaheem/lt-rest:1.0
```
Can I execute this without using docker? If the answer is positive, do you know by any chance how am I supposed to do that?

**Comment by faisalthaheem** [comment]
Hi

Yes you can, however it appears I left in an incorrect address of mongodb, it should be "127.0.0.1" where it says "192.168.100.100" (which was the laptop containing my mongodb, mosquitto and nodered).

I am assuming you have already been able to follow the steps in the wiki page "Quick Start" and your nodered, moquitto and mongodb are running? if yes, you can run the following command to install the python dependencies

`pip3 install numpy h5py pandas pymongo flask scikit-learn keras tensorflow argparse`

once installed you can navigate to ml/jupyter and execute the following command to run
python3 rest-service.py

That should run the rest service, after which you can invoke the following URL's to start the learning process
http://127.0.0.1:5000/learn-thermostat
http://127.0.0.1:5000/learn-state

Once the process complete, you can invoke the following urls by posting the required data to make inference
http://127.0.0.1:5000/classify-thermostat
http://127.0.0.1:5000/classify-state

The above is taken care of by the nodered flows, I just realized the IP address in those flows in incorrect which I will update as I get some spare time.

**Comment by LucasLibra** [comment]
Yes, my node-red, mosquitto and mongodb are running, and I was able to install all those python dependencies. However, when it gets to run the python3 rest-service.py, I am getting the following Error:

```
2019-06-19 12:07:39.091381: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.2 instructions, but these aren't available on your machine.
Aborted (core dumped)

Do you know any ideas to fix it? I am guessing this has some thing to do with the Tensorflow Wheel.
Thanks!!
```

**Comment by LucasNLiborio** [comment]
Yes, my node-red, mosquitto and mongodb are running, and I was able to install all those python dependencies. However, when it gets to run the python3 rest-service.py, I am getting the following Error:

```
2019-06-19 12:07:39.091381: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.2 instructions, but these aren't available on your machine.
Aborted (core dumped)
```

Do you know any ideas to fix it? I am guessing this has some thing to do with the Tensorflow Wheel.
Thanks!!

**Comment by LucasNLiborio** [comment]
Or something to do with the fact that the machine I'm using has a Core Duo processor, and they don't have SSE 4.2 Instructions

**Comment by faisalthaheem** [comment]
You're absolutely right.
If you've installed from official repo with pip then you need a newer CPU
with supported instructions, otherwise compile from sourced yourself an
older release of tensorflow that does not need the sse4.2 instructions.

**Comment by LucasNLiborio** [comment]
I am getting the following error when I run the rest-service.py script
```
Using TensorFlow backend.
Not running in a container
 * Serving Flask app "rest-service" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Started new learn-state.py with process id [24035]
127.0.0.1 - - [24/Jun/2019 15:09:38] "GET /learn-state HTTP/1.1" 200 -
Traceback (most recent call last):
  File "./learn_state.py", line 20, in <module>
    from keras.models import Sequential
ImportError: No module named keras.models
```
Do you have any ideas how to fix it? I know that keras is installed because I can import it in a normal python script, but for some reason this is not working in the learn_state.py and learn_thermostat.py scripts.

Thanks for everything!!

**Comment by LucasNLiborio** [comment]
I was able to fix this problem just by switching line 23 of rest.service.py to:
`p = subprocess.Popen(['python3',s_path,'-d 90'])`

Now I'm getting the following error from shared.py:

`File "/home/ubuntu/Documents/machine-learnt-air-conditioning/ml/jupyter/shared.py", line 24, in getData
    mongoClient = mongo.MongoClient(os.environ['mongodbhost'], 27017)
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'mongodbhost'
`

**Comment by LucasNLiborio** [comment]
Was able to fix the previous problem by just switching the line to mongoClient = mongo.MongoClient() which already has a default value of 'localhost':27017.

Can you tell me how much is the minimal quantity of Data in order to the learning process starts?

**Comment by faisalthaheem** [comment]
lost the track of this project, sorry. still going to reply for any others who may end up here.
 you need around a 1000 records to get the basics working. i uploaded the collected dataset to the repository, a bit of clean up and it should have enough to get the basic model working.
